In [ ]:
#Introduction to Numpy

In [2]:
import numpy as np

In [4]:
array_one=np.array([1,2,3,4])
array_one_one

array([1, 2, 3, 4])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
numbers=[9,8,7,6]
array_two=np.array(numbers)
array_two

array([9, 8, 7, 6])

In [11]:
array_of_zeros=np.zeros([3,4])
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
array_of_one=np.ones([3,4])
array_of_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
array_of_one_int=np.ones([5,4])
array_of_one_int

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#identity matrixx:structure and shape of an identity matrix

In [22]:
array_eye=np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#requirment: by using numpy want to have aeven numbers printed till 30
#normal python...Range function
#numpy...arange


In [24]:
array_of_evens=np.arange(2,31,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])