In [1]:
#Numpy

In [2]:
import numpy as np #UDERSTANDING THE IDENTITY Matrix:

In [5]:
array_eye=np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
#array of floats

In [8]:
array_of_floats=np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
#Creating a 2D(two dimnestional) array

In [9]:
array_2d=np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [10]:
array_2d.shape

(2, 3)

In [17]:
x=array_2d
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [18]:
x.shape

(6,)

In [ ]:
#Requirment: changing the above to 2 dimensinal array?

In [19]:
array_nd=x.reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
array_nd.shape

(2, 3)

In [21]:
array_nd=x.reshape(4,2)#array shape is 6 ,it can not be resahpe (4,2)because 4*2=8 so it will give error
array_nd

ValueError: cannot reshape array of size 6 into shape (4,2)

In [22]:
#printing array:


In [ ]:
#1D array

In [25]:
a=np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [26]:
a.shape

(8,)

In [ ]:
#2D array

In [27]:
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
b.shape

(4, 3)

In [29]:
#3D array

In [30]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [31]:
c.shape

(2, 3, 4)